### ISSUE TITLE
Can't resolve symlink

### ISSUE THREAD

**Issue by Aloxaf** [xPMo/zsh-ls-colors#3]
```zsh
❯ ln -s a b
❯ ./demo b
b → m48;5;196;38;5;232;1
```

git bisect shows that this bug was introdued in 161e132918d6fab8f664bcf6a5444b1e53a01339

**Comment by xPMo** [comment]
Should be fixed in [`68315ac`](https://github.com/xPMo/zsh-ls-colors/commit/68315acc7e3f4611b41f7dd31eaae45f60c25c57)

**Comment by Aloxaf** [comment]
Umm, still error.

```zsh
❯ ./demo b
b → m48;5;196;38;5;232;1
b
```

**Comment by xPMo** [comment]
The demo is putting the link color and the link target in the wrong order. I thought I pushed that with the commit I linked, but I guess not. Pull latest, it should work.

**Comment by Aloxaf** [comment]
Works perfectly, except that `target` is still not handled properly.

> #ln SYMLINK, LINK, LNK  Symbolic link. If you set this to .target. instead of a numerical value, the color is as for the file pointed to.

I made some changes to demo and it seems to work.

```diff
diff --git a/demo b/demo
index a5e468d..7b045a9 100755
--- a/demo
+++ b/demo
@@ -45,7 +45,7 @@ done
 # Alternate manual method:
 for file; do
        ls-color::match-by $file lstat follow
-       if [[ $reply[2] ]]; then
+       if [[ $reply[2] || $reply[1] == target ]]; then
                # This is a symlink
                symlink_color=$reply[1]
                # If broken, use link color for destination
@@ -55,6 +55,7 @@ for file; do
                        # Not broken, update destination color
                        ls-color::match-by $file stat
                        resolved_color=$reply[1]
+                       [[ $symlink_color == target ]] && symlink_color=$reply[1]
                fi
                print '\e['$symlink_color'm'$file'\e[0m → \e['$resolved_color'm'$resolved'\e[0m'
        else
```

BTW, I use https://github.com/trapd00r/LS_COLORS

**Comment by xPMo** [comment]
> #ln SYMLINK, LINK, LNK Symbolic link. If you set this to .target. instead of a numerical value, the color is as for the file pointed to.

Ah, that is a neat feature which I haven't heard of. I tried a few cases, and if `ls` behavior is correct, it should _only_ show the filetype/mode color, not filename. I'll make changes in `::from-mode`.

**Comment by xPMo** [comment]
I've implemented `$modecolors[ln] = target` now. I'll test a little more myself, and then tag a release if you approve.

**Comment by Aloxaf** [comment]
Works perfectly. Thanks for your great work!

**Comment by Aloxaf** [comment]
A small bug: A broken symlink will cause an error message(`ls-color::match-by:zstat:31: /tmp/d: no such file or director`). But the final color is correct.

**Comment by xPMo** [comment]
Fixed, thanks.
